### ISSUE TITLE
Gitcoin hackaton feedback

### ISSUE THREAD

**Issue by jessgusclark** [masterbluecompact/RIF-Identity-QR-Payment-Dapp#1]
Hey! Great submission. I have a few comments for the gitcoin hackathon:

**Frontend**
- Missing dependencies to run the app. I had to manually install `@nuintun/qrcode`
- Once running, there are multiple warnings about variables were created but not used. Please clean these up.
- Refactor some of the code for better readability.
  - Things like :<scan></scan> for example, 
  - move SVGs out of components or into their own components in some sort of /image folder

**Backend**
- npm install won’t run, I got a python error. This may be my machine, I'm unsure. Installing with yarn worked

If you have any questions about these, feel free to reply here, or come join us on the [RSK Slack](http://developers.rsk.co/slack).

**Comment by t0mcr8se** [comment]
@jessgusclark Thank you for your feedback, me and @EehabArbash are gonna be working on this issue, 

do you have any other notes?

**Comment by jessgusclark** [comment]
@masterbluecompact The app worked as described and I was able to create a QR code for an item. The comments above were the issues that I had after running it.

**Comment by EehabArbash** [comment]
@jessgusclark  Thanks for the review, I fixed the issues mentioned above.

**Comment by jessgusclark** [comment]
Hello @EehabArbash , thanks for fixing those. When I run the app now, I am getting errors regarding invalid Props, and invalid  DOM properties. It is now not running on my machine. 

<img width="1110" alt="Screen Shot 2021-06-14 at 6 02 24 PM" src="https://user-images.githubusercontent.com/766679/121914140-ad0c6500-cd3a-11eb-806f-d4bafdf90906.png">

**Comment by t0mcr8se** [comment]
@jessgusclark thanks for your feedback, we'll fix this today and we'll let you know, anything else?

**Comment by t0mcr8se** [comment]
@jessgusclark all errors about invalid properties are fixed now, there are still some errors from rsk apis and rpc side, but the app is working fine for us. 
![image](https://user-images.githubusercontent.com/62181123/121961678-646f9e80-cd70-11eb-91ce-2df4bc232dfa.png)

Please let me know if you're have any problems running the app..

**Comment by jessgusclark** [comment]
Hey! I tested it out and it works great! Thanks for fixing it, and sorry about the late notice.

**Comment by t0mcr8se** [comment]
@jessgusclark Thank you for your feedback, no problem
